[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "5.0.0-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "7.2.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.36.21"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.23"

[[constraint]]
  branch = "master"
  name = "github.com/skarademir/naturalsort"

[[constraint]]
  name = "github.com/vmware/govcloudair"
  version = "0.0.2"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "0.6.2"

[[constraint]]
  name = "github.com/intel-go/cpuid"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
